[workspace]
members = [
    "orderbook-quoter-server",
    "exchange-stream",
    "exchange-controller",
    "testing/depth-generator",
    "testing/exchange-stubs",
    "internal-objects",
    "market-objects",
]
