[package]
name = "keyrock-main"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "orderbook-quoter-server",
    "exchange-stream",
    "exchange-controller",
    "testing/depth-generator",
    "testing/exchange-stubs",
    "internal-objects",
    "market-objects",
    "orderbook",
    "config",
]
exclude = [
    "market-maker",
    "exchange-server"
]

[dependencies]
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
prost = "0.11"

[build-dependencies]
prost = "0.11"
tonic-build = { version = "0.9.2", features = ["prost"] }
serde = "1.0.166"
serde_yaml = "0.9.22"
config = { path = "config"}


