exchanges:
  - client_name: "binance_usa_1"
    host_uri:
    exchange_name: 1
    snapshot_enabled: true
    http_client: true
    snapshot_uri: "http://localhost:5000"
    ws_uri: "wss://localhost:5001"
    ws_poll_rate_milliseconds: 99
    depth: 5000
    buffer_size: 2048
    watched_pair: "USDTBTC"
  - client_name: "binance_usa_2"
    host_uri:
    exchange_name: 2
    snapshot_enabled: true
    http_client: true
    snapshot_uri: "http://localhost:6000"
    ws_uri: "wss://localhost:6001"
    ws_poll_rate_milliseconds: 99
    depth: 5000
    buffer_size: 2048
    watched_pair: "USDTBTC"
orderbook:
  exchange_count: 2
  depth: 5000
  tick_size: 0.01
  mid_price: 2700
  ticker: "BTCUSDT"
  ring_buffer:
    ring_buffer_size: 1024
    channel_buffer_size: 512
grpc_server:
  host_uri: "127.0.0.1:5000"
