[package]
name = "quoter-errors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.17"
serde_json = "1.0.142"
thiserror = "1.0.40"
tokio-tungstenite = "0.18.0"
