[package]
name = "exchange"
version = "0.1.0"
edition = "2021"

[dependencies]
config.workspace = true
market-objects.workspace = true
depth-pool.workspace = true
quoter-errors.workspace = true
cyper.workspace = true
tokio.workspace = true
crossbeam-channel.workspace = true
futures.workspace = true
serde_json.workspace = true
futures-util.workspace = true
tracing.workspace = true
itertools.workspace = true
pin-project-lite.workspace = true
arrayvec = { git = "https://github.com/bluss/arrayvec" }
compio.workspace = true
thiserror = "1.0.40"
kanal = "0.1.1"

[dev-dependencies]
exchange-stubs.workspace = true
testing-traits.workspace = true
