io_thread_percentage: 0.6
exchanges:
  - client_name: "binance_usa_1"
    host_uri:
    exchange_name: 2
    snapshot_enabled: true
    http_client: true
    snapshot_uri: "http://localhost:8081/depths"
    ws_uri: "wss://localhost:8080"
    depth: 5000
    buffer_size: 2048
    watched_pair: "USDT/BTC"
  - client_name: "binance_usa_2"
    host_uri:
    exchange_name: 2
    snapshot_enabled: true
    http_client: true
    snapshot_uri: "http://localhost:8083/depths"
    ws_uri: "wss://localhost:8082"
    depth: 5000
    buffer_size: 2048
    watched_pair: "USDT/BTC"
orderbook:
  exchange_count: 2
  depth: 200
  tick_size: 0.01
  mid_price: 2700
  ticker: "BTC/USDT"
  ring_buffer:
    ring_buffer_size: 1024
    channel_buffer_size: 512
grpc_server:
  host_uri: "127.0.0.1:5000"
