io_thread_percentage: 0.6
exchanges:
  - client_name: "binance_usa_1"
    host_uri:
    exchange_name: 2
    snapshot_enabled: true
    http_client: true
    snapshot_uri: "https://api.binance.us/api/v3/depth?symbol=USDTBTC&limit=5000"
    ws_uri: "wss://stream.binance.us:9443"
    depth: 5000
    buffer_size: 2048
    watched_pair: "USDT/BTC"
    orderbook_subscription_message: "Subscribe to ETH/USD"
orderbook:
  ring_buffer:
    ring_buffer_size: 1024
    channel_buffer_size: 512
  asset_price_floor: 100.0
  asset_price_ceiling: 10000.0
  price_point_array_size: 100
grpc_server:
  host_uri: "127.0.0.1:9090"
