io_thread_percentage: 0.6
exchanges:
  - client_name: "binance_global_1"
    exchange_name: 0
    snapshot_enabled: true
    http_client: true
    snapshot_uri: "https://api.binance.com/api/v3/depth?symbol=USDTBTC&limit=5000"
    ws_uri: "http://ws1.uri"
    depth: 5000
    buffer_size: 1024
    watched_pair: "USDT/BTC"
    orderbook_subscription_message: "Subscribe to BTC/USD"
  - client_name: "binance_usa_1"
    exchange_name: 2
    snapshot_enabled: true
    http_client: true
    snapshot_uri: "https://api.binance.com/api/v3/depth?symbol=USDTBTC&limit=5000"
    ws_uri: "http://ws2.uri"
    depth: 5000
    buffer_size: 2048
    watched_pair: "USDT/BTC"
    orderbook_subscription_message: "Subscribe to ETH/USD"
orderbook:
  ring_buffer:
    ring_buffer_size: 1024
    channel_buffer_size: 512
  asset_price_floor: 100.0
  asset_price_ceiling: 10000.0
  price_point_array_size: 100
grpc_server:
  address: "127.0.0.1"
  port: 5000
