[package]
name = "depth-driver"
version = "0.1.0"
edition = "2021"

[dependencies]
depth-pool.workspace = true
crossbeam-channel.workspace = true
futures.workspace = true
tracing.workspace = true
futures-util.workspace = true
tokio.workspace = true
serde_json.workspace = true
config.workspace = true
exchange.workspace = true
market-objects.workspace = true
quoter-errors.workspace = true
anyhow = "1.0.99"
compio.workspace = true
kanal = "0.1.1"
